### PR TITLE
Enable garnix CI

### PR DESCRIPTION
**Pull request by Gabriella439**

### CODE REVIEW

**Comment by jkarni** [comment]
aarch64-darwin is by default disabled, so nothing gets built here. See https://garnix.io/docs/yaml_config for enabling it. 

I'll add a *hint* to the output whenever there are packages being ignored so this is clearer!

**Comment by Gabriella439** [comment]
@jkarni: Wait, I thought this `garnix.yaml` does enable `aarch64-darwin` builds.  Is the configuration missing an additional line somewhere?

**Comment by jkarni** [comment]
Maybe the extra apostrophe at the end? Not near a computer to check.

There aren't x86 darwin, by the way, only aarch64. And we don't build apps,
only checks, packages, devShells, and nixosConfigurations for now.

**Comment by Gabriella439** [comment]
Yep, it was the apostrophes.  Thanks for the help!

**Pull request merged**
